Feature/buchungskorrektur (#122)
* NEW: Manuelle Korrektur Verwendungszweck

* NEW: Automatische Korrektur Verwendungszweck bei Buchungsübernahme aus Hibiscus

* Update symbol for Buchungskorrektur Menu

* Add possibility of deactivating the automatic correction of usage purposes

- Checkbox "Automatische Korrektur der Verwendungszecke ... "

* Change order in navigation menu Buchführung

* Fix NullPointerException in getBuchungsZweckKorrektur

java.lang.NullPointerException: Cannot invoke "String.replace(java.lang.CharSequence, java.lang.CharSequence)" because "value" is null

* Format code snippet

* Fix spelling mistakes

* resolve conflict

---------

Co-authored-by: Dennis Schlevoigt <schlevoigt@visus.com>
Co-authored-by: dippeal <info@dippe-it.de>